apiVersion: v2
name: ml-platform
description: Umbrella chart for Istio, Cert-Manager, and KServe
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: cert-manager
    version: v1.14.4
    repository: "file://charts/cert-manager-v1.14.4.tgz"

  - name: istio-base
    version: 1.20.0
    repository: "file://charts/istio-base-1.20.0.tgz"

  - name: istiod
    version: 1.20.0
    repository: "file://charts/istiod-1.20.0.tgz"
    dependsOn:
      - istio-base

  - name: istio-gateway
    version: 1.20.0
    repository: "file://charts/istio-gateway-1.20.0.tgz"
    dependsOn:
      - istiod

  - name: kserve-crd
    version: 0.13.0
    repository: "file://charts/kserve-crd-0.13.0.tgz"
    dependsOn:
      - istio-gateway

  - name: kserve-controller
    version: 0.13.0
    repository: "file://charts/kserve-0.13.0.tgz"
    dependsOn:
      - kserve-crd
