helmDefaults:
  wait: true
  timeout: 800
  atomic: false

releases:
  - name: kserve-crd
    namespace: kserve
    createNamespace: true
    chart: C:/Users/Admin/Documents/ML-OPS/kubernates/crds/charts/kserve-crd-v0.13.0.tgz

  - name: kserve-controller
    namespace: kserve
    createNamespace: false
    chart: C:/Users/Admin/Documents/ML-OPS/kubernates/crds/charts/kserve-v0.13.0.tgz
